In [1]:
import numpy as np 
import pandas as pd

In [85]:
df=pd.read_csv("stock_data_aug_2025.csv")

In [86]:
df.head()

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology
1,2025-07-01,ABBV,187.01,189.97,191.84,186.30,14831744,3.226888e+11,14.09,3.48,13.48,255.99,158.77,Healthcare
2,2025-07-01,ABT,115.83,113.90,117.36,112.75,18439336,1.898333e+11,24.09,1.70,4.73,131.38,83.47,Healthcare
3,2025-07-01,ADBE,598.97,597.43,604.53,594.05,32093085,2.588863e+11,41.74,0.00,14.31,802.91,422.60,Technology
4,2025-07-01,ADP,248.69,248.51,249.30,247.11,3084969,1.023276e+11,31.30,2.22,7.94,274.26,228.28,Financials

In [87]:
df

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology
1,2025-07-01,ABBV,187.01,189.97,191.84,186.30,14831744,3.226888e+11,14.09,3.48,13.48,255.99,158.77,Healthcare
2,2025-07-01,ABT,115.83,113.90,117.36,112.75,18439336,1.898333e+11,24.09,1.70,4.73,131.38,83.47,Healthcare
3,2025-07-01,ADBE,598.97,597.43,604.53,594.05,32093085,2.588863e+11,41.74,0.00,14.31,802.91,422.60,Technology
4,2025-07-01,ADP,248.69,248.51,249.30,247.11,3084969,1.023276e+11,31.30,2.22,7.94,274.26,228.28,Financials
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2537,2025-07-31,VRTX,497.89,500.67,501.77,495.00,11392799,1.303828e+11,28.69,0.00,17.45,611.12,443.16,Healthcare
2538,2025-07-31,VZ,42.53,43.10,43.68,42.37,11071330,1.676111e+11,8.73,6.27,4.94,54.28,36.52,Communication Services
2539,2025-07-31,WMT,74.90,76.43,76.70,74.70,8936394,5.986126e+11,31.49,1.29,2.43,85.04,69.46,Consumer Staples
2540,2025-07-31,XOM,128.89,125.65,129.79,124.54,33058998,4.923429e+11,15.51,3.37,8.10,148.15,100.89,Energy
2541,2025-07-31,ZTS,151.32,152.13,153.57,150.99,9751816,6.896560e+10,25.96,0.64,5.86,184.55,128.48,Healthcare

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542 entries, 0 to 2541
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2542 non-null   object
 1   Ticker          2542 non-null   object
 2   Open Price      2542 non-null   float64
 3   Close Price     2542 non-null   float64
 4   High Price      2542 non-null   float64
 5   Low Price       2542 non-null   float64
 6   Volume Traded   2542 non-null   int64
 7   Market Cap      2542 non-null   float64
 8   PE Ratio        2542 non-null   float64
 9   Dividend Yield  2542 non-null   float64
 10  EPS             2542 non-null   float64
 11  52 Week High    2542 non-null   float64
 12  52 Week Low     2542 non-null   float64
 13  Sector          2542 non-null   object
dtypes: float64(10), int64(1), object(3)
memory usage: 278.2+ KB

In [89]:
df["Ticker"].value_counts()

Ticker
AAPL    31
ABBV    31
ABT     31
ADBE    31
ADP     31
        ..
VRTX    31
VZ      31
WMT     31
XOM     31
ZTS     31
Name: count, Length: 82, dtype: int64

In [90]:
df['Date'] = pd.to_datetime(df['Date'])

In [91]:
df = df.sort_values(['Ticker', 'Date'])

In [92]:
df

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology
82,2025-07-02,AAPL,196.35,193.97,197.20,192.71,70814457,3.027824e+12,29.68,0.49,6.54,223.63,165.72,Technology
164,2025-07-03,AAPL,189.91,184.33,191.41,183.57,47615959,2.877346e+12,30.99,0.48,5.95,207.84,155.53,Technology
246,2025-07-04,AAPL,200.14,194.50,202.40,193.12,28273707,3.036098e+12,30.59,0.48,6.36,224.50,148.88,Technology
328,2025-07-05,AAPL,223.56,226.27,227.63,221.67,49156551,3.532020e+12,31.50,0.46,7.18,303.81,171.34,Technology
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2213,2025-07-27,ZTS,153.21,151.69,154.63,150.47,11365871,6.876613e+10,26.33,0.72,5.76,184.31,106.30,Healthcare
2295,2025-07-28,ZTS,148.87,147.16,150.72,145.46,13074745,6.671253e+10,23.04,0.66,6.39,166.82,118.05,Healthcare
2377,2025-07-29,ZTS,151.99,154.06,155.92,150.35,5193986,6.984053e+10,23.12,0.72,6.66,204.89,108.69,Healthcare
2459,2025-07-30,ZTS,149.31,152.07,153.08,147.26,5695826,6.893840e+10,27.26,0.76,5.58,186.25,131.29,Healthcare
2541,2025-07-31,ZTS,151.32,152.13,153.57,150.99,9751816,6.896560e+10,25.96,0.64,5.86,184.55,128.48,Healthcare

In [93]:
df.isnull().sum()

Date              0
Ticker            0
Open Price        0
Close Price       0
High Price        0
Low Price         0
Volume Traded     0
Market Cap        0
PE Ratio          0
Dividend Yield    0
EPS               0
52 Week High      0
52 Week Low       0
Sector            0
dtype: int64

In [94]:
df['Ticker'] = df['Ticker'].astype('category')
df['Sector'] = df['Sector'].astype('category')

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2542 entries, 0 to 2541
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2542 non-null   datetime64[ns]
 1   Ticker          2542 non-null   category
 2   Open Price      2542 non-null   float64
 3   Close Price     2542 non-null   float64
 4   High Price      2542 non-null   float64
 5   Low Price       2542 non-null   float64
 6   Volume Traded   2542 non-null   int64
 7   Market Cap      2542 non-null   float64
 8   PE Ratio        2542 non-null   float64
 9   Dividend Yield  2542 non-null   float64
 10  EPS             2542 non-null   float64
 11  52 Week High    2542 non-null   float64
 12  52 Week Low     2542 non-null   float64
 13  Sector          2542 non-null   category
dtypes: category(2), datetime64[ns](1), float64(10), int64(1)
memory usage: 266.2 KB

In [96]:
df['return'] = df.groupby('Ticker')['Close Price'].pct_change()

C:\Users\LOQ\AppData\Local\Temp\ipykernel_30804\737178825.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['return'] = df.groupby('Ticker')['Close Price'].pct_change()

In [97]:
df['return']

0            NaN
82     -0.061496
164    -0.049698
246     0.055173
328     0.163342
          ...
2213    0.012414
2295   -0.029864
2377    0.046888
2459   -0.012917
2541    0.000395
Name: return, Length: 2542, dtype: float64

In [98]:
df

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector,return
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology,NaN
82,2025-07-02,AAPL,196.35,193.97,197.20,192.71,70814457,3.027824e+12,29.68,0.49,6.54,223.63,165.72,Technology,-0.061496
164,2025-07-03,AAPL,189.91,184.33,191.41,183.57,47615959,2.877346e+12,30.99,0.48,5.95,207.84,155.53,Technology,-0.049698
246,2025-07-04,AAPL,200.14,194.50,202.40,193.12,28273707,3.036098e+12,30.59,0.48,6.36,224.50,148.88,Technology,0.055173
328,2025-07-05,AAPL,223.56,226.27,227.63,221.67,49156551,3.532020e+12,31.50,0.46,7.18,303.81,171.34,Technology,0.163342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2213,2025-07-27,ZTS,153.21,151.69,154.63,150.47,11365871,6.876613e+10,26.33,0.72,5.76,184.31,106.30,Healthcare,0.012414
2295,2025-07-28,ZTS,148.87,147.16,150.72,145.46,13074745,6.671253e+10,23.04,0.66,6.39,166.82,118.05,Healthcare,-0.029864
2377,2025-07-29,ZTS,151.99,154.06,155.92,150.35,5193986,6.984053e+10,23.12,0.72,6.66,204.89,108.69,Healthcare,0.046888
2459,2025-07-30,ZTS,149.31,152.07,153.08,147.26,5695826,6.893840e+10,27.26,0.76,5.58,186.25,131.29,Healthcare,-0.012917
2541,2025-07-31,ZTS,151.32,152.13,153.57,150.99,9751816,6.896560e+10,25.96,0.64,5.86,184.55,128.48,Healthcare,0.000395

In [99]:
df.head(10)

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector,return
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology,NaN
82,2025-07-02,AAPL,196.35,193.97,197.20,192.71,70814457,3.027824e+12,29.68,0.49,6.54,223.63,165.72,Technology,-0.061496
164,2025-07-03,AAPL,189.91,184.33,191.41,183.57,47615959,2.877346e+12,30.99,0.48,5.95,207.84,155.53,Technology,-0.049698
246,2025-07-04,AAPL,200.14,194.50,202.40,193.12,28273707,3.036098e+12,30.59,0.48,6.36,224.50,148.88,Technology,0.055173
328,2025-07-05,AAPL,223.56,226.27,227.63,221.67,49156551,3.532020e+12,31.50,0.46,7.18,303.81,171.34,Technology,0.163342
410,2025-07-06,AAPL,186.46,183.21,188.80,182.62,59631220,2.859863e+12,29.35,0.49,6.24,234.85,138.94,Technology,-0.190304
492,2025-07-07,AAPL,187.72,189.16,191.67,186.99,71116100,2.952741e+12,32.08,0.52,5.90,218.10,150.71,Technology,0.032476
574,2025-07-08,AAPL,196.27,201.24,203.29,193.98,63114261,3.141307e+12,27.12,0.47,7.42,249.12,178.25,Technology,0.063861
656,2025-07-09,AAPL,208.27,210.87,213.89,205.16,39473188,3.291629e+12,24.15,0.49,8.73,261.22,164.57,Technology,0.047853
738,2025-07-10,AAPL,202.31,197.07,203.46,196.04,49547600,3.076215e+12,32.19,0.46,6.12,254.45,152.68,Technology,-0.065443

In [100]:
df['return'] = df['return'].fillna(0)

In [101]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [102]:
x= df.iloc[:,2:-2]

In [103]:
x

,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low
0,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54
82,196.35,193.97,197.20,192.71,70814457,3.027824e+12,29.68,0.49,6.54,223.63,165.72
164,189.91,184.33,191.41,183.57,47615959,2.877346e+12,30.99,0.48,5.95,207.84,155.53
246,200.14,194.50,202.40,193.12,28273707,3.036098e+12,30.59,0.48,6.36,224.50,148.88
328,223.56,226.27,227.63,221.67,49156551,3.532020e+12,31.50,0.46,7.18,303.81,171.34
...,...,...,...,...,...,...,...,...,...,...,...
2213,153.21,151.69,154.63,150.47,11365871,6.876613e+10,26.33,0.72,5.76,184.31,106.30
2295,148.87,147.16,150.72,145.46,13074745,6.671253e+10,23.04,0.66,6.39,166.82,118.05
2377,151.99,154.06,155.92,150.35,5193986,6.984053e+10,23.12,0.72,6.66,204.89,108.69
2459,149.31,152.07,153.08,147.26,5695826,6.893840e+10,27.26,0.76,5.58,186.25,131.29
2541,151.32,152.13,153.57,150.99,9751816,6.896560e+10,25.96,0.64,5.86,184.55,128.48

In [104]:
y= df['return']

In [105]:
x_test, x_train, y_test, y_train = train_test_split(x, y, test_size=0.2, random_state=42)

In [106]:
reg= LinearRegression()

In [107]:
reg.fit(x_train, y_train)

LinearRegression()

In [108]:
y_pred= reg.predict(x_test)

In [109]:
y_pred

array([-0.12667388, -0.004291  , -0.00609513, ..., -0.00017947,
       -0.00155063, -0.01131311], shape=(2033,))

In [110]:
y_test

749    -0.027734
403     0.078099
1465   -0.012615
1037    0.040608
325    -0.053642
          ...
2184   -0.012894
855    -0.065059
1184   -0.022839
1927    0.003014
1913   -0.028353
Name: return, Length: 2033, dtype: float64

In [111]:
df

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector,return
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology,0.000000
82,2025-07-02,AAPL,196.35,193.97,197.20,192.71,70814457,3.027824e+12,29.68,0.49,6.54,223.63,165.72,Technology,-0.061496
164,2025-07-03,AAPL,189.91,184.33,191.41,183.57,47615959,2.877346e+12,30.99,0.48,5.95,207.84,155.53,Technology,-0.049698
246,2025-07-04,AAPL,200.14,194.50,202.40,193.12,28273707,3.036098e+12,30.59,0.48,6.36,224.50,148.88,Technology,0.055173
328,2025-07-05,AAPL,223.56,226.27,227.63,221.67,49156551,3.532020e+12,31.50,0.46,7.18,303.81,171.34,Technology,0.163342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2213,2025-07-27,ZTS,153.21,151.69,154.63,150.47,11365871,6.876613e+10,26.33,0.72,5.76,184.31,106.30,Healthcare,0.012414
2295,2025-07-28,ZTS,148.87,147.16,150.72,145.46,13074745,6.671253e+10,23.04,0.66,6.39,166.82,118.05,Healthcare,-0.029864
2377,2025-07-29,ZTS,151.99,154.06,155.92,150.35,5193986,6.984053e+10,23.12,0.72,6.66,204.89,108.69,Healthcare,0.046888
2459,2025-07-30,ZTS,149.31,152.07,153.08,147.26,5695826,6.893840e+10,27.26,0.76,5.58,186.25,131.29,Healthcare,-0.012917
2541,2025-07-31,ZTS,151.32,152.13,153.57,150.99,9751816,6.896560e+10,25.96,0.64,5.86,184.55,128.48,Healthcare,0.000395

In [129]:
monthly = df.groupby('Ticker').agg(
    Sector=('Sector','first'),
    First_Close=('Close Price','first'),
    Last_Close=('Close Price','last')
).reset_index()

monthly['Total_Return'] = monthly['Last_Close'] / monthly['First_Close'] - 1

C:\Users\LOQ\AppData\Local\Temp\ipykernel_30804\1378395248.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  monthly = df.groupby('Ticker').agg(

In [133]:
monthly

,Ticker,Sector,First_Close,Last_Close,Total_Return,Rank,Label
0,AAPL,Technology,206.68,199.68,-0.033869,11.0,0
1,ABBV,Healthcare,189.97,185.25,-0.024846,14.0,0
2,ABT,Healthcare,113.90,120.32,0.056365,3.0,0
3,ADBE,Technology,597.43,612.31,0.024907,3.0,0
4,ADP,Financials,248.51,253.55,0.020281,5.0,0
...,...,...,...,...,...,...,...
77,VRTX,Healthcare,477.72,500.67,0.048041,5.0,0
78,VZ,Communication Services,46.03,43.10,-0.063654,6.0,0
79,WMT,Consumer Staples,70.57,76.43,0.083038,2.0,0
80,XOM,Energy,115.68,125.65,0.086186,2.0,0
81,ZTS,Healthcare,153.51,152.13,-0.008990,11.0,0

In [131]:
monthly['Rank'] = monthly.groupby('Sector')['Total_Return'].rank(
    ascending=False, method='dense'
)

monthly['Label'] = (monthly['Rank'] == 1).astype(int)

C:\Users\LOQ\AppData\Local\Temp\ipykernel_30804\3635386432.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  monthly['Rank'] = monthly.groupby('Sector')['Total_Return'].rank(

In [134]:
monthly.head(15)

,Ticker,Sector,First_Close,Last_Close,Total_Return,Rank,Label
0,AAPL,Technology,206.68,199.68,-0.033869,11.0,0
1,ABBV,Healthcare,189.97,185.25,-0.024846,14.0,0
2,ABT,Healthcare,113.90,120.32,0.056365,3.0,0
3,ADBE,Technology,597.43,612.31,0.024907,3.0,0
4,ADP,Financials,248.51,253.55,0.020281,5.0,0
5,AMD,Technology,175.47,165.17,-0.058699,12.0,0
6,AMGN,Healthcare,314.21,298.52,-0.049935,16.0,0
7,AMT,Real Estate,203.17,201.70,-0.007235,2.0,0
8,AMZN,Consumer Discretionary,182.09,171.97,-0.055577,6.0,0
9,AVGO,Technology,1666.58,1635.99,-0.018355,7.0,0
10,BAC,Financials,45.26,40.29,-0.109810,15.0,0
11,BKNG,Consumer Discretionary,3632.24,3856.57,0.061761,3.0,0
12,BLK,Financials,864.14,873.35,0.010658,7.0,0
13,BMY,Healthcare,54.12,56.62,0.046194,6.0,0
14,BRK.B,Financials,438.02,450.09,0.027556,3.0,0

In [135]:
monthly

,Ticker,Sector,First_Close,Last_Close,Total_Return,Rank,Label
0,AAPL,Technology,206.68,199.68,-0.033869,11.0,0
1,ABBV,Healthcare,189.97,185.25,-0.024846,14.0,0
2,ABT,Healthcare,113.90,120.32,0.056365,3.0,0
3,ADBE,Technology,597.43,612.31,0.024907,3.0,0
4,ADP,Financials,248.51,253.55,0.020281,5.0,0
...,...,...,...,...,...,...,...
77,VRTX,Healthcare,477.72,500.67,0.048041,5.0,0
78,VZ,Communication Services,46.03,43.10,-0.063654,6.0,0
79,WMT,Consumer Staples,70.57,76.43,0.083038,2.0,0
80,XOM,Energy,115.68,125.65,0.086186,2.0,0
81,ZTS,Healthcare,153.51,152.13,-0.008990,11.0,0

In [137]:
monthly.head(20)

,Ticker,Sector,First_Close,Last_Close,Total_Return,Rank,Label
0,AAPL,Technology,206.68,199.68,-0.033869,11.0,0
1,ABBV,Healthcare,189.97,185.25,-0.024846,14.0,0
2,ABT,Healthcare,113.90,120.32,0.056365,3.0,0
3,ADBE,Technology,597.43,612.31,0.024907,3.0,0
4,ADP,Financials,248.51,253.55,0.020281,5.0,0
5,AMD,Technology,175.47,165.17,-0.058699,12.0,0
6,AMGN,Healthcare,314.21,298.52,-0.049935,16.0,0
7,AMT,Real Estate,203.17,201.70,-0.007235,2.0,0
8,AMZN,Consumer Discretionary,182.09,171.97,-0.055577,6.0,0
9,AVGO,Technology,1666.58,1635.99,-0.018355,7.0,0
10,BAC,Financials,45.26,40.29,-0.109810,15.0,0
11,BKNG,Consumer Discretionary,3632.24,3856.57,0.061761,3.0,0
12,BLK,Financials,864.14,873.35,0.010658,7.0,0
13,BMY,Healthcare,54.12,56.62,0.046194,6.0,0
14,BRK.B,Financials,438.02,450.09,0.027556,3.0,0
15,C,Financials,64.13,65.52,0.021675,4.0,0
16,CAT,Industrials,359.92,375.44,0.043121,1.0,1
17,CB,Financials,234.81,246.05,0.047868,2.0,0
18,COST,Consumer Staples,872.74,833.30,-0.045191,7.0,0
19,CRM,Technology,281.25,258.46,-0.081031,15.0,0

In [138]:
monthly['Sector'].value_counts()

Sector
Healthcare                18
Financials                15
Technology                15
Consumer Discretionary     7
Industrials                7
Consumer Staples           7
Communication Services     6
Utilities                  3
Energy                     2
Real Estate                2
Name: count, dtype: int64

In [139]:
df = df.merge(
    monthly[['Ticker', 'Total_Return', 'Rank', 'Label']],
    on='Ticker',
    how='left'
)

In [140]:
df

,Date,Ticker,Open Price,Close Price,High Price,Low Price,Volume Traded,Market Cap,PE Ratio,Dividend Yield,EPS,52 Week High,52 Week Low,Sector,return,Total_Return,Rank,Label
0,2025-07-01,AAPL,209.02,206.68,210.48,205.01,53813618,3.226224e+12,27.38,0.52,7.55,231.45,173.54,Technology,0.000000,-0.033869,11.0,0
1,2025-07-02,AAPL,196.35,193.97,197.20,192.71,70814457,3.027824e+12,29.68,0.49,6.54,223.63,165.72,Technology,-0.061496,-0.033869,11.0,0
2,2025-07-03,AAPL,189.91,184.33,191.41,183.57,47615959,2.877346e+12,30.99,0.48,5.95,207.84,155.53,Technology,-0.049698,-0.033869,11.0,0
3,2025-07-04,AAPL,200.14,194.50,202.40,193.12,28273707,3.036098e+12,30.59,0.48,6.36,224.50,148.88,Technology,0.055173,-0.033869,11.0,0
4,2025-07-05,AAPL,223.56,226.27,227.63,221.67,49156551,3.532020e+12,31.50,0.46,7.18,303.81,171.34,Technology,0.163342,-0.033869,11.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2537,2025-07-27,ZTS,153.21,151.69,154.63,150.47,11365871,6.876613e+10,26.33,0.72,5.76,184.31,106.30,Healthcare,0.012414,-0.008990,11.0,0
2538,2025-07-28,ZTS,148.87,147.16,150.72,145.46,13074745,6.671253e+10,23.04,0.66,6.39,166.82,118.05,Healthcare,-0.029864,-0.008990,11.0,0
2539,2025-07-29,ZTS,151.99,154.06,155.92,150.35,5193986,6.984053e+10,23.12,0.72,6.66,204.89,108.69,Healthcare,0.046888,-0.008990,11.0,0
2540,2025-07-30,ZTS,149.31,152.07,153.08,147.26,5695826,6.893840e+10,27.26,0.76,5.58,186.25,131.29,Healthcare,-0.012917,-0.008990,11.0,0
2541,2025-07-31,ZTS,151.32,152.13,153.57,150.99,9751816,6.896560e+10,25.96,0.64,5.86,184.55,128.48,Healthcare,0.000395,-0.008990,11.0,0

In [141]:
features = [
    'Open Price', 'Close Price', 'High Price', 'Low Price',
    'Volume Traded', 'Market Cap', 'PE Ratio', 'Dividend Yield',
    'EPS', '52 Week High', '52 Week Low'
]

In [142]:
X = df[features]
y = df['Label']

In [143]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

In [144]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [145]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [146]:
# Logistic Regression
log_model = LogisticRegression(max_iter=2000)
log_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=2000)

In [147]:
# Decision Tree
tree_model = DecisionTreeClassifier(max_depth=5, random_state=42)
tree_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [148]:
# SVM
svm_model = SVC(kernel='rbf', C=1)
svm_model.fit(X_train_scaled, y_train)

SVC(C=1)

In [149]:
y_pred_log = log_model.predict(X_test_scaled)
y_pred_tree = tree_model.predict(X_test)
y_pred_svm = svm_model.predict(X_test_scaled)

In [150]:
print("\n📌 Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

print("\n📌 Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))
print(classification_report(y_test, y_pred_tree))

print("\n📌 SVM Accuracy:", accuracy_score(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

📌 Logistic Regression Accuracy: 0.8773584905660378
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       558
           1       0.00      0.00      0.00        78

    accuracy                           0.88       636
   macro avg       0.44      0.50      0.47       636
weighted avg       0.77      0.88      0.82       636


📌 Decision Tree Accuracy: 0.9323899371069182
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       558
           1       0.75      0.67      0.71        78

    accuracy                           0.93       636
   macro avg       0.85      0.82      0.83       636
weighted avg       0.93      0.93      0.93       636


📌 SVM Accuracy: 0.8773584905660378
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       558
           1       0.00      0.00      0.00        78

    accuracy                           0.88       636
   macro avg       0.44      0.50      0.47       636
weighted avg       0.77      0.88      0.82       636

c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\LOQ\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [2]:
data= pd.read_csv("infolimpioavanzadoTarget.csv")

In [3]:
data

,date,open,high,low,close,adjclose,volume,ticker,RSIadjclose15,RSIvolume15,...,high-15,K-15,D-15,stochastic-k-15,stochastic-d-15,stochastic-kd-15,volumenrelativo,diff,INCREMENTO,TARGET
0,2022-01-03,17.799999,18.219000,17.500000,17.760000,17.760000,106600,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.919758,-1.900001,-9.664295,0
1,2022-01-04,17.700001,18.309999,17.620001,17.660000,17.660000,128700,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.110440,-1.379999,-7.247895,0
2,2022-01-05,17.580000,17.799999,16.910000,16.950001,16.950001,103100,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.889560,-0.930000,-5.201344,0
3,2022-01-06,16.650000,16.879999,16.139999,16.170000,16.170000,173600,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.497843,-0.360000,-2.177856,0
4,2022-01-07,16.219999,16.290001,15.630000,15.710000,15.710000,137800,ASLE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.188956,-0.120000,-0.758054,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7776,2022-12-23,23.250000,23.540001,23.250000,23.290001,22.699928,4900,ATLO,60.782255,47.081752,...,23.600000,26.223672,27.022465,26.223672,27.022465,-0.798793,0.333333,NaN,NaN,0
7777,2022-12-27,23.350000,23.610001,23.250000,23.350000,22.758406,9200,ATLO,62.022801,47.747952,...,23.610001,30.764722,28.003602,30.764722,28.003602,2.761119,0.625850,NaN,NaN,0
7778,2022-12-28,23.450001,23.570000,23.219999,23.350000,22.758406,15200,ATLO,62.022801,48.713225,...,23.610001,30.764722,29.251039,30.764722,29.251039,1.513683,1.034014,NaN,NaN,0
7779,2022-12-29,23.330000,23.740000,23.330000,23.610001,23.011820,7100,ATLO,67.186408,47.445460,...,23.740000,46.457382,35.995609,46.457382,35.995609,10.461773,0.482993,NaN,NaN,0
7780,2022-12-30,23.680000,23.760000,23.610001,23.610001,23.011820,7100,ATLO,67.186408,47.445460,...,23.760000,45.784072,41.002059,45.784072,41.002059,4.782013,0.482993,NaN,NaN,0